use_frameworks!
inhibit_all_warnings!
target 'JHRecruit' do
    pod 'MyLayout', '~> 1.4.3'
    pod 'LFLiveKit'
    pod 'AFNetworking'
    pod 'MJExtension'
    pod 'SDWebImage'
    pod 'MJRefresh'
    pod 'Socket.IO-Client-Swift'
    pod 'SDCycleScrollView'
    pod 'SVProgressHUD'



end
